CryptoAlerts/urls.py
from django.contrib import admin
from django.urls import path, include  # Assurez-vous d'importer include

urlpatterns = [
    path('', include(('alerts.urls', 'alerts'), namespace='alerts')),
    path('accounts/', include('allauth.urls')),
]

alerts/urls.py
from django.urls import path
from . import views

app_name = 'alerts'

urlpatterns = [
    path('', views.alert_list, name='alert_list'),

    path('create/', views.alert_create, name='alert_create'),

    path('<int:pk>/', views.alert_detail, name='alert_detail'),

    path('<int:pk>/update/', views.alert_update, name='alert_update'),

    path('<int:pk>/delete/', views.alert_delete, name='alert_delete'),

    path('fetch-rate/', views.fetch_rate, name='fetch-rate'),

    path('update-rate/<int:pk>/', views.update_rate, name='update_rate'),
]

alerts/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError


class Alert(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE, related_name='alerts')
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    base = models.CharField(max_length=10, default='BTC', choices=[(sym, sym) for sym in ['BTC', 'ETH', 'USD', 'EUR']])
    quote = models.CharField(max_length=10, default='USD', choices=[(sym, sym) for sym in ['BTC', 'ETH', 'USD', 'EUR']])
    threshold_value = models.DecimalField(max_digits=20, default=5000, decimal_places=8)
    rate = models.DecimalField(max_digits=20, decimal_places=8, null=True, blank=True)
    warning = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.name} - {self.user.username}"

    def clean(self):
        # Custom validation to ensure base_currency and quote_currency are not the same
        if self.base == self.quote:
            raise ValidationError("Base currency and quote currency must be different.")

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

alerts/forms.py
from django import forms
from .models import Alert

class AlertForm(forms.ModelForm):
    class Meta:
        model = Alert
        fields = ['name', 'description', 'base', 'quote', 'threshold_value']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Ex: Alert for Bitcoin Drop'}),
            'description': forms.Textarea(attrs={'placeholder': 'Describe the conditions for the alert.'}),
            'base': forms.Select(attrs={'class': 'form-control'}),
            'quote': forms.Select(attrs={'class': 'form-control'}),
            'threshold_value': forms.NumberInput(attrs={'placeholder': 'Enter threshold value'}),
        }

CryptoAlerts/views.py
from django.shortcuts import render
from datetime import datetime
import requests

# def index(request):
#     return render(request, "index.html", context={'prenom': 'patrick', 'date': datetime.today()})
#

alerts/views.py
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
import json
import requests
from dotenv import load_dotenv
import os
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Alert
from .forms import AlertForm
from django.contrib import messages
from django.utils.dateparse import parse_datetime



load_dotenv()
@login_required
def alert_detail(request, pk):
    alert = get_object_or_404(Alert, pk=pk, user=request.user)
    # rate = fetch_data(alert.base, alert.quote)
    # print(rate)
    # return render(request, 'alerts/alert_detail.html', {'alert': alert, 'rate': rate, 'base': alert.base})
    return render(request, 'alerts/alert_detail.html', {'alert': alert, 'threshold_value': alert.threshold_value})


@login_required
def alert_list(request):
    alerts = Alert.objects.filter(user=request.user)
    ordered_alerts = alerts.order_by('-id')
    return render(request, 'alerts/alert_list.html', {'alerts': alerts, 'ordered_alerts':  ordered_alerts})


@login_required
def alert_create(request):
    if request.method == 'POST':
        form = AlertForm(request.POST)
        if form.is_valid():
            alert = form.save(commit=False)
            alert.user = request.user
            alert.save()
            return redirect('alerts:alert_detail', pk=alert.id)
    else:
        form = AlertForm()

    return render(request, 'alerts/alert_form.html', {'form': form})


@login_required
def alert_update(request, pk):
    alert = get_object_or_404(Alert, pk=pk, user=request.user)  # Get the Alert object, ensuring the current user owns it
    if request.method == 'POST':
        form = AlertForm(request.POST, instance=alert)
        if form.is_valid():
            form.save()
            return redirect('alerts:alert_detail', pk=alert.pk)
    else:
        form = AlertForm(instance=alert)

    return render(request, 'alerts/alert_form.html', {'form': form, 'alert': alert})


@login_required
def alert_delete(request, pk):
    alert = get_object_or_404(Alert, pk=pk, user=request.user)
    if request.method == 'POST':
        alert.delete()
        messages.success(request, 'Alert deleted successfully!')
        return redirect('alerts:alert_list')

def fetch_data(base, quote):
    url = f"https://rest.coinapi.io/v1/exchangerate/{base}"
    api_key = os.getenv('COINAPI_KEY3')
    headers = {"X-CoinAPI-Key": api_key}
    response = requests.get(url, headers=headers)
    data = response.json()
    if 'rates' in data:
        for rate_info in data['rates']:
            if rate_info.get('asset_id_quote') == quote:
                return rate_info.get('rate')

def fetch_rate(request):
    base = request.GET.get('base')
    quote = request.GET.get('quote')
    rate = fetch_data(base, quote)
    if rate is not None:
        return JsonResponse({'rate': rate})
    else:
        return JsonResponse({'rate': 0})


@csrf_exempt  # Only use this if you know what you are doing regarding CSRF protection!
@require_POST
def update_rate(request, pk):
    if request.method == 'POST':
        data = json.loads(request.body)
        rate = data.get('rate')
        updated_at_str = data.get('updated_at')
        updated_at = parse_datetime(updated_at_str)
        alert = get_object_or_404(Alert, pk=pk, user=request.user)
        alert.rate = rate
        alert.updated_at = updated_at
        alert.save()
        return JsonResponse({'success': True})
    return JsonResponse({'success': False, 'error': 'Invalid request'}, status=400)

CryptoAlerts/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>bonjour {{ prenom }} ca va ?</h1>
    <h2>aujourd'hui nous sommes le {{ date|date:"d F Y" }}</h2>
</body>
</html>

alerts/templates/alerts/alert_detail.html
<!-- Template pour les détails d'une alerte -->
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Détail de l'Alerte</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script>
        const base = "{{ alert.base }}";
        const quote = "{{ alert.quote }}";
        const alertId = "{{ alert.pk }}";

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        function saveExchangeRate(rate, time) {
            fetch(`/update-rate/${alertId}/`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'X-CSRFToken': getCookie('csrftoken'),
                },
                body: JSON.stringify({ rate: rate, updated_at: time })
            })
            .then(response => {
                if (response.ok) {
                    return response.json();
                } else {
                    throw new Error('Server returned non-OK status: ' + response.status);
                }
            })
            .then(data => {
                if (data.success) {
                    console.log('Rate saved successfully');
                } else {
                    console.error('Error in response:', data.error);
                }
            })
            .catch(error => console.error('Error saving rate:', error));
        }

        function updateExchangeRate() {
            fetch(`/fetch-rate/?base=${base}&quote=${quote}`)
                .then(response => {
                    return response.json();
                })
                .then(data => {
                    if (data.rate !== 0) {
                        document.getElementById('exchange_rate').textContent = data.rate.toFixed(4); // Format the rate to 4 decimal places
                        document.getElementById('exchange_time').textContent = new Date().toLocaleTimeString();
                        saveExchangeRate(data.rate.toFixed(4), new Date().toLocaleTimeString());
                    }
                    else {
                        alert("En raison du nombre de requetes limitées, attendre une minute avant de recharger la page :)")
                    }
                });
        }

        document.addEventListener('DOMContentLoaded', updateExchangeRate);

        setInterval(updateExchangeRate, 180000);
    </script>

</head>
<body>
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/random/?money/);">
        <div class="container">
            <div class="row">
                <div class="col-12">
                <h1 class="display-4">{{ alert.name }}</h1>
                </div>
            </div>
            <a class="btn btn-primary my-5" href="{% url 'alerts:alert_list' %}">back to the list</a>
        </div>
    </div>

    <div class="container justify-content-center">
        <p>Description : {{ alert.description }}</p>
        <p>Base : {{ alert.base }}</p>
        <p>Quote : {{ alert.quote }}</p>
        <p>limite: {{ alert.threshold_value }}</p>
        <p>created at: {{ alert.created_at }}</p>
        <p>updated at :
            <span id="exchange_time">
                {% if alert.updated_at %}
                    {{ alert.updated_at }}
                {% endif %}
            </span>
        </p>
        <p>rate :
            <span id="exchange_rate">
            {% if alert.rate %}
                {{ alert.rate }}
                {% if alert.rate < alert.threshold_value %}
                    <div id="alert_message" style="color: red;">
                        Attention: Le taux de change est inférieur au seuil!
                    </div>
                {% endif %}
            {% endif %}
            </span>
        </p>
        <a href="{% url 'alerts:alert_update' alert.pk %}">Éditer</a>
        <form action="{% url 'alerts:alert_delete' alert.pk %}" method="post" onsubmit="return confirm('Are you sure you want to delete this alert?');">
            {% csrf_token %}
            <button type="submit">supprimer</button>
        </form>
    </div>
</body>
</html>

alerts/templates/alerts/alert_form.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{% if alert %}Éditer{% else %}Créer{% endif %} Alerte</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <h2>{% if alert %}Éditer{% else %}Créer{% endif %} Alerte</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                {% if alert %}
                    Mettre à jour
                {% else %}
                    Créer
                {% endif %}
            </button>
        </form>
        <a href="{% url 'alerts:alert_list' %}">Annuler</a>
    </div>
</body>
</html>

alerts/templates/alerts/alert_list.html
<!-- Template pour lister les alertes -->
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Liste des Alertes</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>



<body>

    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/random/?money/);">
        <div class="container">
            <div class="py-4">
              <h1>CoinAlert, a simple cryptocurrency notification app using CoinApi!</h1>
            </div>
            <div class="py-3">
                <p>Manage your own cryptocurrency alerts</p>
            </div>
            <div class="py-3 rounded-3">
                <a class="btn btn-primary" href="{% url 'alerts:alert_create' %}">Create a new alert</a>
            </div>
        </div>
    </div>



    <div class="container text-center">
        <div class="my-5">
            <h2>My Alerts</h2>
        </div>
        <div class="row gy-5 my-5">
            {% for alert in ordered_alerts %}
                <a href="{% url 'alerts:alert_detail' alert.pk %}" class="card col-3 m-3 p-0" style="width: 18rem; text-decoration: none;">
                    <img class="card-img-top img-cover" src="https://source.unsplash.com/random/?money/{{ timestamp|stringformat:'i' }}{{ alert.id }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{alert.name}}</h5>
                        <p class="card-text">{{alert.description}}</p>
                    </div>
                </a>
            {% empty %}
                <li>Aucune alerte disponible.</li>
            {% endfor %}
        </div>
    </div>
    <nav class="navbar fixed-bottom navbar-light bg-light d-flex justify-content-center">
      <div class="navbar-brand fs-6" href="#">Cette plateforme a été concu selon un cahier des charges bien précis et suivi à la lettre par le developpeur.</div>
    </nav>

</body>
</html>